import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <main className="max-w-4xl mx-auto p-4">
          <Header />
          {children}
          <footer className="border-t p-8 text-center text-gray-500">
            &#169;	2021 Coffee Tribe. All rights reserved.
          </footer>
        </main>
      </body>
    </html>
  );
}
